[project]
name = "stock-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "config",
]

[build-system]
requires = ["hatchling"] # Or "flit_core", "setuptools"
build-backend = "hatchling.build"

[tool.uv.sources]
config = { workspace = true }
